# AnvilRepair

settings:
  # Choose if players pay a fixed amount for repair or a X amount per durability points missing
  payPerDurability: true
  # Choose if there's a base price (Must be enabled if payPerDurability is false, else repairing will be free)
  payBasePrice: true
  guiTitle: "&cRepair Interface"

formats:
  repairItem: "&cRepairing"
  repairItemWithName: "&cRepairing <name>"
  repairItemNamePerTick: "&c."
  guiCost:
    - ""
    - "&cCost: &f<price>"

prices:
  # The amount that each durability point will cost
  pricePerDurability: 5
  # The amount that repairing will cost regardless of durability missing
  basePrice: 200

messages:
  notHoldingAnything: "&cYou're not holding anything."
  notRepairable: "&cThis item cannot be repaired."
  alreadyRepaired: "&cThis item does not need any repairing."
  notEnoughMoney: "&cInsufficient funds."
  acceptMessage: "&c-<price>"

repairableItems:
  - 256
  - 257
  - 258
  - 259
  - 261
  - 267
  - 268
  - 269
  - 270
  - 271
  - 272
  - 273
  - 274
  - 275
  - 276
  - 277
  - 278
  - 279
  - 283
  - 284
  - 285
  - 286
  - 290
  - 291
  - 292
  - 293
  - 294
  - 298
  - 299
  - 300
  - 301
  - 302
  - 303
  - 304
  - 305
  - 306
  - 307
  - 308
  - 309
  - 310
  - 311
  - 312
  - 313
  - 314
  - 315
  - 316
  - 317
  - 346
  - 359

version: 1